name: Monitor Safe Multisigs

on:
  schedule:
    - cron: "0/10 * * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  multisig:
    uses: ./.github/workflows/_run-monitoring.yml
    secrets: inherit
    with:
      cache_file: nonces.txt
      cache_key_prefix: nonces-v3
      scripts: |
        safe/main.py
